Repository afet-yonetim-sistemi/ays-be-api-automation, pull requests merged in 2023-12, with the labels that each got.

#101 Project Configurations Have Been Refactored
  .gitignore
  configuration.properties
  pom.xml
  sample_configuration.properties
  src/test/java/logs/automation.log
  src/test/reports/Test-Report-2023.09.28.04.00.54 .html
Labels: refactor, in review

#104 #2 - CODEOWNERS file edited.
  CODEOWNERS
Labels: in review

#107 PostAdminRegistrationApplicationsTest added
  src/test/java/endpoints/Authorization.java
  src/test/java/endpoints/InstitutionEndpoints.java
  src/test/java/endpoints/Routes.java
  src/test/java/payload/FilterForInstitution.java
  src/test/java/payload/RequestBodyInstitution.java
  src/test/java/payload/Sort.java
  src/test/java/payload/SuperAdminCredentials.java
  src/test/java/tests/institution/adminregistrationmanagementservice/PostAdminRegistrationApplicationsTest.java
Labels: in development
